name_or_path: HuggingFaceH4/zephyr-7b-beta
tokenizer_name_or_path: null
reference: null
archive: null
block_name: LlamaDecoderLayer

policy_dtype: bfloat16
fsdp_policy_mp: null
reference_dtype: bfloat16